#!/bin/sh

TEST_DIR=test-cases/
TEST_FILE=test-cases/arguments/operators.txt

case $1 in

    test)
        RUST_BACKTRACE=1 cargo test && cargo run -- -t ${2:-$TEST_DIR} && cargo clippy
        ;;

    watch)
        case $2 in

            test)
                RUST_BACKTRACE=1 watchexec -w src -w ${3:-$TEST_DIR} -w Cargo.toml -c -- "cargo test && cargo run -q -- --test ${3:-$TEST_DIR} && cargo clippy"
                ;;

            **)
                RUST_BACKTRACE=1 watchexec -w src -w ${2:-$TEST_FILE} -w Cargo.toml -c -- cargo run -q -- ${2:-$TEST_FILE}
                ;;

        esac
        ;;


    doc)
        cargo doc --open
        ;;

    count-lines)
        tokei
        ;;

    **)
        cargo run -q -- ${1:-$TEST_FILE}
    ;;

esac
