#!/bin/sh

case $1 in

    test)
        RUST_BACKTRACE=1 cargo test && cargo run -- -t test-cases && cargo clippy
        ;;

    watch)
        RUST_BACKTRACE=1 watchexec -w src -w test-cases -w Cargo.toml -c -- "cargo test && cargo run -- -t test-cases && cargo clippy"
        ;;

    doc)
        cargo doc --open
        ;;

    count-lines)
        tokei
        ;;

    **)
        cargo run -q -- ${1:-test-cases/simple.txt}
    ;;

esac
