[package]
name = "footle"
version = "0.1.0"
authors = ["Geoff Leyland <geoff.leyland@incremental.co.nz>"]
edition = "2024"

[dependencies]
git-version = "0.3.9"
typed-arena = "2.0.2"
enumset = "1.1.14"
bit-set = "0.11"
libc = "0.2"
capstone = { version = "0.14", features = ["arch_arm64"], optional=true }
paste = "1.0.15"
anyhow = "1.0.104"
pico-args = "0.5.0"

[features]
dogfood = ["dep:capstone"]

[lints.rust]
future_incompatible = { level = "warn", priority = -1 }

[lints.clippy]
all = { level = "warn", priority = -2 }
pedantic = { level = "warn", priority = -2 }
nursery = { level = "warn", priority = -2 }
enum_glob_use = "allow"
missing_const_for_fn = "allow"
wildcard_imports = "allow"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
